In [1]:
import pandas as pd
df = pd.read_csv('/Users/keva/Downloads/finance_loan_portfolio_python_dataset.csv')

In [2]:
df.head()

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
0,FIN-00255,CUST-00839,Arjun Gupta,64.0,Female,Jaipur,Self-Employed,679000.0,707.0,Home Loan,...,7,Yes,0.920,42160.72,78362.21,High,2026-05-30,Auto-Debit,Partner,Nagpur Civil Lines
1,FIN-00474,CUST-00508,Rohan Iyer,63.0,Male,Mumbai,Salaried,1275000.0,745.0,Personal Loan,...,0,No,0.386,167007.37,435254.86,Low,2026-07-10,Net Banking,Website,Chennai T Nagar
2,FIN-00725,CUST-00013,Rohan Jadhav,48.0,Female,Lucknow,Government Employee,1390000.0,663.0,Personal Loan,...,2,No,NaN,6378.50,0.00,Low,NaN,UPI,Branch,Nashik Road
3,FIN-00438,CUST-00328,Tanvi Chaudhary,56.0,Male,Nashik,Government Employee,719000.0,695.0,Vehicle Loan,...,1,No,0.689,353397.61,148295.33,Medium,2026-06-24,Auto-Debit,Website,Delhi Connaught Place
4,FIN-00661,CUST-00740,Rahul Iyer,53.0,Female,Nashik,Business Owner,7218000.0,665.0,Home Loan,...,3,No,0.075,1210618.96,1460036.03,Medium,2026-04-24,UPI,Branch,Jaipur C Scheme

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record_ID                1230 non-null   object
 1   Customer_ID              1230 non-null   object
 2   Customer_Name            1230 non-null   object
 3   Age                      1202 non-null   float64
 4   Gender                   1208 non-null   object
 5   City                     1198 non-null   object
 6   Employment_Type          1205 non-null   object
 7   Annual_Income_INR        1196 non-null   float64
 8   Credit_Score             1188 non-null   float64
 9   Loan_Type                1230 non-null   object
 10  Loan_Amount_INR          1230 non-null   int64
 11  Interest_Rate_Pct        1212 non-null   float64
 12  Loan_Term_Months         1230 non-null   int64
 13  Monthly_EMI_INR          1230 non-null   float64
 14  Disbursement_Date        1230 non-null   object
 15  Outstanding_Balance_INR  1206 non-null   float64
 16  Payment_Status           1230 non-null   object
 17  Days_Past_Due            1230 non-null   int64
 18  Late_Payment_Count       1230 non-null   int64
 19  Default_Flag             1230 non-null   object
 20  Debt_to_Income_Ratio     1195 non-null   float64
 21  Savings_Balance_INR      1199 non-null   float64
 22  Investment_Value_INR     1198 non-null   float64
 23  Risk_Category            1230 non-null   object
 24  Last_Payment_Date        1203 non-null   object
 25  Payment_Mode             1210 non-null   object
 26  Acquisition_Channel      1230 non-null   object
 27  Branch_Name              1230 non-null   object
dtypes: float64(9), int64(4), object(15)
memory usage: 269.2+ KB

In [4]:
df.shape

(1230, 28)

In [5]:
df.describe()

,Age,Annual_Income_INR,Credit_Score,Loan_Amount_INR,Interest_Rate_Pct,Loan_Term_Months,Monthly_EMI_INR,Outstanding_Balance_INR,Days_Past_Due,Late_Payment_Count,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR
count,1202.000000,1.196000e+03,1188.000000,1.230000e+03,1212.000000,1230.000000,1230.000000,1.206000e+03,1230.000000,1230.000000,1195.000000,1.199000e+03,1.198000e+03
mean,42.964226,1.386089e+06,684.171717,1.674126e+06,13.708251,70.048780,41653.180146,1.034594e+06,27.930894,2.666667,0.530249,2.852790e+05,2.484833e+05
std,12.896096,1.028175e+06,74.048875,1.861600e+06,4.011314,66.095999,43479.570285,1.720638e+06,48.114059,2.696973,0.265499,3.354904e+05,3.662194e+05
min,21.000000,2.940000e+05,474.000000,4.500000e+04,7.200000,6.000000,1845.090000,0.000000e+00,0.000000,0.000000,0.050000,0.000000e+00,0.000000e+00
25%,32.000000,7.382500e+05,634.000000,4.600000e+05,10.630000,24.000000,15239.642500,0.000000e+00,0.000000,0.000000,0.299000,5.866674e+04,1.853671e+04
50%,43.000000,1.134500e+06,685.000000,9.750000e+05,13.015000,48.000000,29093.575000,3.322209e+05,0.000000,2.000000,0.494000,1.785311e+05,1.314216e+05
75%,54.000000,1.647500e+06,733.000000,2.201250e+06,16.560000,84.000000,53039.820000,1.249156e+06,44.000000,4.000000,0.780000,3.909735e+05,3.178733e+05
max,65.000000,7.292000e+06,850.000000,1.127000e+07,24.000000,300.000000,472335.630000,1.047749e+07,180.000000,13.000000,0.920000,3.202587e+06,3.942651e+06

In [6]:
df.describe(include="all")

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
count,1230,1230,1230,1202.000000,1208,1198,1205,1.196000e+03,1188.000000,1230,...,1230.000000,1230,1195.000000,1.199000e+03,1.198000e+03,1230,1203,1210,1230,1230
unique,1200,653,602,NaN,3,15,5,NaN,NaN,6,...,NaN,2,NaN,NaN,NaN,3,406,5,5,10
top,FIN-00977,CUST-00421,Kabir Verma,NaN,Male,Mumbai,Salaried,NaN,NaN,Personal Loan,...,NaN,No,NaN,NaN,NaN,Medium,2026-07-01,Auto-Debit,Mobile App,Nagpur Civil Lines
freq,2,6,8,NaN,596,221,552,NaN,NaN,362,...,NaN,1009,NaN,NaN,NaN,514,28,469,382,134
mean,NaN,NaN,NaN,42.964226,NaN,NaN,NaN,1.386089e+06,684.171717,NaN,...,2.666667,NaN,0.530249,2.852790e+05,2.484833e+05,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,12.896096,NaN,NaN,NaN,1.028175e+06,74.048875,NaN,...,2.696973,NaN,0.265499,3.354904e+05,3.662194e+05,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,2.940000e+05,474.000000,NaN,...,0.000000,NaN,0.050000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,32.000000,NaN,NaN,NaN,7.382500e+05,634.000000,NaN,...,0.000000,NaN,0.299000,5.866674e+04,1.853671e+04,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,43.000000,NaN,NaN,NaN,1.134500e+06,685.000000,NaN,...,2.000000,NaN,0.494000,1.785311e+05,1.314216e+05,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,54.000000,NaN,NaN,NaN,1.647500e+06,733.000000,NaN,...,4.000000,NaN,0.780000,3.909735e+05,3.178733e+05,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,7.292000e+06,850.000000,NaN,...,13.000000,NaN,0.920000,3.202587e+06,3.942651e+06,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isnull()

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1226,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1227,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1228,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1229,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Record_ID                   0
Customer_ID                 0
Customer_Name               0
Age                        28
Gender                     22
City                       32
Employment_Type            25
Annual_Income_INR          34
Credit_Score               42
Loan_Type                   0
Loan_Amount_INR             0
Interest_Rate_Pct          18
Loan_Term_Months            0
Monthly_EMI_INR             0
Disbursement_Date           0
Outstanding_Balance_INR    24
Payment_Status              0
Days_Past_Due               0
Late_Payment_Count          0
Default_Flag                0
Debt_to_Income_Ratio       35
Savings_Balance_INR        31
Investment_Value_INR       32
Risk_Category               0
Last_Payment_Date          27
Payment_Mode               20
Acquisition_Channel         0
Branch_Name                 0
dtype: int64

In [10]:
#for numeric values column
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [11]:
df["Annual_Income_INR"] = df["Annual_Income_INR"].fillna(df["Annual_Income_INR"].mean())

In [12]:
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].mean())

In [13]:
df["Loan_Amount_INR"] = df["Loan_Amount_INR"].fillna(df["Loan_Amount_INR"].mean())

In [14]:
df["Interest_Rate_Pct"] = df["Interest_Rate_Pct"].fillna(df["Interest_Rate_Pct"].mean())

In [15]:
df["Loan_Term_Months"] = df["Loan_Term_Months"].fillna(df["Loan_Term_Months"].mean())

In [16]:
df["Monthly_EMI_INR"] = df["Monthly_EMI_INR"].fillna(df["Monthly_EMI_INR"].mean())

In [17]:
df["Outstanding_Balance_INR"] = df["Outstanding_Balance_INR"].fillna(df["Outstanding_Balance_INR"].mean())

In [18]:
df["Days_Past_Due"] = df["Days_Past_Due"].fillna(df["Days_Past_Due"].mean())

In [19]:
df["Late_Payment_Count"] = df["Late_Payment_Count"].fillna(df["Late_Payment_Count"].mean())

In [20]:
df["Debt_to_Income_Ratio"] = df["Debt_to_Income_Ratio"].fillna(df["Debt_to_Income_Ratio"].mean())

In [21]:
df["Debt_to_Income_Ratio"] = df["Debt_to_Income_Ratio"].fillna(df["Debt_to_Income_Ratio"].mean())

In [22]:
df["Investment_Value_INR"] = df["Investment_Value_INR"].fillna(df["Investment_Value_INR"].mean())

In [28]:
#for text/object column
df["Gender"] = df["Gender"].fillna("Unknown Gender")

In [30]:
df["City"] = df["City"].fillna("Unknown City")

In [31]:
df["Employment_Type"] = df["Employment_Type"].fillna("Unknown Employment_Type")

In [33]:
df.duplicated().sum()

np.int64(30)

In [34]:
df = df.drop_duplicates()

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.shape

(1200, 28)

In [37]:
#unique values in each object column
df['Gender'].unique()

array(['Female', 'Male', 'Non-Binary'], dtype=object)

In [41]:
df['Gender'].nunique()

3

In [39]:
df['Gender'].value_counts()

Gender
Male          606
Female        565
Non-Binary     29
Name: count, dtype: int64

In [40]:
df['City'].unique()

array(['Jaipur', 'Mumbai', 'Lucknow', 'Nashik', 'Chennai', 'Delhi',
       'Indore', 'Ahmedabad', 'Bengaluru', 'Hyderabad', 'Pune', 'Thane',
       'Surat', 'Kolkata', 'Nagpur'], dtype=object)

In [42]:
df['City'].nunique()

15

In [43]:
df['City'].value_counts()

City
Mumbai       248
Pune         166
Bengaluru     85
Delhi         81
Thane         74
Hyderabad     69
Nashik        62
Nagpur        62
Chennai       59
Surat         53
Jaipur        50
Lucknow       49
Kolkata       49
Indore        47
Ahmedabad     46
Name: count, dtype: int64

In [44]:
df['Employment_Type'].unique()

array(['Self-Employed', 'Salaried', 'Government Employee',
       'Business Owner', 'Freelancer'], dtype=object)

In [45]:
df['Employment_Type'].nunique()

5

In [46]:
df['Employment_Type'].value_counts()

Employment_Type
Salaried               563
Self-Employed          208
Business Owner         168
Freelancer             145
Government Employee    116
Name: count, dtype: int64

In [47]:
df.value_counts(["Gender","City"])

Gender      City
Male        Mumbai       141
Female      Mumbai        99
Male        Pune          85
Female      Pune          79
            Bengaluru     47
            Delhi         43
Male        Delhi         38
            Bengaluru     36
Female      Thane         36
Male        Thane         35
            Hyderabad     35
            Surat         32
Female      Nagpur        32
            Hyderabad     32
            Nashik        31
Male        Nashik        30
Female      Chennai       29
Male        Nagpur        29
            Chennai       28
            Ahmedabad     27
Female      Lucknow       26
            Jaipur        26
            Indore        24
Male        Jaipur        24
Female      Kolkata       23
Male        Lucknow       22
            Kolkata       22
            Indore        22
Female      Ahmedabad     19
            Surat         19
Non-Binary  Mumbai         8
            Kolkata        4
            Thane          3
            Bengaluru      2
            Chennai        2
            Hyderabad      2
            Pune           2
            Surat          2
            Indore         1
            Lucknow        1
            Nagpur         1
            Nashik         1
Name: count, dtype: int64

In [48]:
df.value_counts(["Gender","Employment_Type"])

Gender      Employment_Type
Male        Salaried               281
Female      Salaried               274
Male        Self-Employed          111
Female      Self-Employed           90
Male        Business Owner          82
Female      Business Owner          79
            Freelancer              70
Male        Freelancer              70
            Government Employee     62
Female      Government Employee     52
Non-Binary  Salaried                 8
            Business Owner           7
            Self-Employed            7
            Freelancer               5
            Government Employee      2
Name: count, dtype: int64

In [49]:
df.value_counts(["City","Employment_Type"])

City       Employment_Type
Mumbai     Salaried               110
Pune       Salaried                76
Mumbai     Self-Employed           52
Bengaluru  Salaried                42
Delhi      Salaried                38
                                 ...
Chennai    Business Owner           3
Kolkata    Freelancer               3
Lucknow    Government Employee      3
Jaipur     Freelancer               2
Indore     Government Employee      2
Name: count, Length: 75, dtype: int64

In [ ]:
#groupby()

In [50]:
df.columns

Index(['Record_ID', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City',
       'Employment_Type', 'Annual_Income_INR', 'Credit_Score', 'Loan_Type',
       'Loan_Amount_INR', 'Interest_Rate_Pct', 'Loan_Term_Months',
       'Monthly_EMI_INR', 'Disbursement_Date', 'Outstanding_Balance_INR',
       'Payment_Status', 'Days_Past_Due', 'Late_Payment_Count', 'Default_Flag',
       'Debt_to_Income_Ratio', 'Savings_Balance_INR', 'Investment_Value_INR',
       'Risk_Category', 'Last_Payment_Date', 'Payment_Mode',
       'Acquisition_Channel', 'Branch_Name'],
      dtype='object')

In [51]:
df.groupby("Gender")["Annual_Income_INR"].mean()

Gender
Female        1.368431e+06
Male          1.405117e+06
Non-Binary    1.570141e+06
Name: Annual_Income_INR, dtype: float64

In [52]:
df.groupby("Gender")["Annual_Income_INR"].max()

Gender
Female        7218000.0
Male          7292000.0
Non-Binary    4404000.0
Name: Annual_Income_INR, dtype: float64

In [53]:
df.groupby("Gender")["Annual_Income_INR"].min()

Gender
Female        306000.0
Male          294000.0
Non-Binary    494000.0
Name: Annual_Income_INR, dtype: float64

In [54]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum()

Loan_Type
Business Loan     338690000
Education Loan    169825000
Gold Loan          53425000
Home Loan         937635000
Personal Loan     187300000
Vehicle Loan      323160000
Name: Loan_Amount_INR, dtype: int64

In [55]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum()

Loan_Type       Risk_Category
Business Loan   High              87005000
                Low               48055000
                Medium           203630000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Gold Loan       High               1240000
                Low               18480000
                Medium            33705000
Home Loan       High             383155000
                Low              144405000
                Medium           410075000
Personal Loan   High              26700000
                Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
                Low              106720000
                Medium           144530000
Name: Loan_Amount_INR, dtype: int64

In [56]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type       Risk_Category
Home Loan       Medium           410075000
                High             383155000
Business Loan   Medium           203630000
Vehicle Loan    Medium           144530000
Home Loan       Low              144405000
Vehicle Loan    Low              106720000
Business Loan   High              87005000
Personal Loan   Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Business Loan   Low               48055000
Gold Loan       Medium            33705000
Personal Loan   High              26700000
Gold Loan       Low               18480000
                High               1240000
Name: Loan_Amount_INR, dtype: int64

In [ ]:
#ASSIGNMENTS QUESTIONS & ANSWERS

In [57]:
#1.How many total loan records are present in the cleaned dataset?
df.shape

(1200, 28)

In [59]:
#2. How many unique customers are present in the dataset?
df['Customer_ID'].nunique()

653

In [65]:
#3. How many customers have more than one loan record?
df['Customer_ID'].value_counts()

Customer_ID
CUST-00528    6
CUST-00689    6
CUST-00397    5
CUST-00040    5
CUST-00465    5
             ..
CUST-00506    1
CUST-00302    1
CUST-00108    1
CUST-00143    1
CUST-00030    1
Name: count, Length: 653, dtype: int64

In [66]:
#4. What are the unique loan types available in the dataset?
df['Customer_ID'].unique()

array(['CUST-00839', 'CUST-00508', 'CUST-00013', 'CUST-00328',
       'CUST-00740', 'CUST-00334', 'CUST-00824', 'CUST-00542',
       'CUST-00580', 'CUST-00522', 'CUST-00138', 'CUST-00356',
       'CUST-00172', 'CUST-00866', 'CUST-00714', 'CUST-00045',
       'CUST-00032', 'CUST-00794', 'CUST-00451', 'CUST-00529',
       'CUST-00656', 'CUST-00186', 'CUST-00630', 'CUST-00289',
       'CUST-00205', 'CUST-00530', 'CUST-00732', 'CUST-00764',
       'CUST-00362', 'CUST-00514', 'CUST-00017', 'CUST-00083',
       'CUST-00267', 'CUST-00122', 'CUST-00379', 'CUST-00616',
       'CUST-00497', 'CUST-00065', 'CUST-00175', 'CUST-00785',
       'CUST-00008', 'CUST-00643', 'CUST-00808', 'CUST-00664',
       'CUST-00397', 'CUST-00094', 'CUST-00605', 'CUST-00624',
       'CUST-00373', 'CUST-00687', 'CUST-00539', 'CUST-00297',
       'CUST-00697', 'CUST-00532', 'CUST-00611', 'CUST-00223',
       'CUST-00268', 'CUST-00778', 'CUST-00049', 'CUST-00150',
       'CUST-00067', 'CUST-00404', 'CUST-00361', 'CUST-00319',
       'CUST-00810', 'CUST-00443', 'CUST-00653', 'CUST-00863',
       'CUST-00488', 'CUST-00330', 'CUST-00055', 'CUST-00135',
       'CUST-00448', 'CUST-00180', 'CUST-00095', 'CUST-00228',
       'CUST-00783', 'CUST-00374', 'CUST-00854', 'CUST-00161',
       'CUST-00822', 'CUST-00751', 'CUST-00663', 'CUST-00251',
       'CUST-00287', 'CUST-00632', 'CUST-00553', 'CUST-00219',
       'CUST-00717', 'CUST-00774', 'CUST-00527', 'CUST-00533',
       'CUST-00325', 'CUST-00064', 'CUST-00016', 'CUST-00625',
       'CUST-00535', 'CUST-00392', 'CUST-00054', 'CUST-00421',
       'CUST-00435', 'CUST-00114', 'CUST-00026', 'CUST-00755',
       'CUST-00502', 'CUST-00516', 'CUST-00836', 'CUST-00023',
       'CUST-00734', 'CUST-00198', 'CUST-00582', 'CUST-00750',
       'CUST-00461', 'CUST-00460', 'CUST-00519', 'CUST-00322',
       'CUST-00133', 'CUST-00056', 'CUST-00060', 'CUST-00691',
       'CUST-00648', 'CUST-00290', 'CUST-00113', 'CUST-00308',
       'CUST-00301', 'CUST-00612', 'CUST-00217', 'CUST-00256',
       'CUST-00336', 'CUST-00019', 'CUST-00386', 'CUST-00035',
       'CUST-00411', 'CUST-00838', 'CUST-00597', 'CUST-00862',
       'CUST-00418', 'CUST-00040', 'CUST-00465', 'CUST-00174',
       'CUST-00414', 'CUST-00573', 'CUST-00406', 'CUST-00147',
       'CUST-00425', 'CUST-00646', 'CUST-00220', 'CUST-00694',
       'CUST-00431', 'CUST-00293', 'CUST-00419', 'CUST-00635',
       'CUST-00445', 'CUST-00521', 'CUST-00415', 'CUST-00084',
       'CUST-00120', 'CUST-00703', 'CUST-00121', 'CUST-00517',
       'CUST-00018', 'CUST-00727', 'CUST-00427', 'CUST-00536',
       'CUST-00520', 'CUST-00029', 'CUST-00342', 'CUST-00885',
       'CUST-00736', 'CUST-00294', 'CUST-00154', 'CUST-00282',
       'CUST-00780', 'CUST-00153', 'CUST-00752', 'CUST-00840',
       'CUST-00490', 'CUST-00847', 'CUST-00321', 'CUST-00412',
       'CUST-00724', 'CUST-00900', 'CUST-00215', 'CUST-00403',
       'CUST-00428', 'CUST-00692', 'CUST-00526', 'CUST-00203',
       'CUST-00685', 'CUST-00503', 'CUST-00880', 'CUST-00564',
       'CUST-00039', 'CUST-00182', 'CUST-00080', 'CUST-00237',
       'CUST-00669', 'CUST-00455', 'CUST-00304', 'CUST-00713',
       'CUST-00790', 'CUST-00284', 'CUST-00739', 'CUST-00606',
       'CUST-00859', 'CUST-00709', 'CUST-00746', 'CUST-00634',
       'CUST-00168', 'CUST-00639', 'CUST-00326', 'CUST-00835',
       'CUST-00299', 'CUST-00433', 'CUST-00450', 'CUST-00221',
       'CUST-00538', 'CUST-00201', 'CUST-00659', 'CUST-00384',
       'CUST-00844', 'CUST-00684', 'CUST-00849', 'CUST-00578',
       'CUST-00528', 'CUST-00592', 'CUST-00872', 'CUST-00805',
       'CUST-00544', 'CUST-00015', 'CUST-00620', 'CUST-00595',
       'CUST-00621', 'CUST-00484', 'CUST-00119', 'CUST-00005',
       'CUST-00252', 'CUST-00678', 'CUST-00895', 'CUST-00705',
       'CUST-00479', 'CUST-00009', 'CUST-00012', 'CUST-00354',
       'CUST-00524', 'CUST-00188', 'CUST-00261', 'CUST-00556',
       'CUST-00892', 'CUST-00708', 'CUST-00803', 'CUST-00292',
       'CUST-00867', 'CUST-00561', 'CUST-00043', 'CUST-00210',
       'CUST-00873', 'CUST-00899', 'CUST-00280', 'CUST-00695',
       'CUST-00274', 'CUST-00614', 'CUST-00058', 'CUST-00626',
       'CUST-00509', 'CUST-00259', 'CUST-00216', 'CUST-00518',
       'CUST-00851', 'CUST-00791', 'CUST-00241', 'CUST-00101',
       'CUST-00213', 'CUST-00523', 'CUST-00110', 'CUST-00396',
       'CUST-00531', 'CUST-00320', 'CUST-00327', 'CUST-00329',
       'CUST-00741', 'CUST-00099', 'CUST-00792', 'CUST-00768',
       'CUST-00677', 'CUST-00096', 'CUST-00706', 'CUST-00158',
       'CUST-00046', 'CUST-00303', 'CUST-00471', 'CUST-00725',
       'CUST-00257', 'CUST-00676', 'CUST-00178', 'CUST-00057',
       'CUST-00254', 'CUST-00652', 'CUST-00511', 'CUST-00645',
       'CUST-00098', 'CUST-00316', 'CUST-00877', 'CUST-00641',
       'CUST-00071', 'CUST-00623', 'CUST-00742', 'CUST-00547',
       'CUST-00115', 'CUST-00125', 'CUST-00864', 'CUST-00815',
       'CUST-00036', 'CUST-00882', 'CUST-00474', 'CUST-00865',
       'CUST-00493', 'CUST-00758', 'CUST-00636', 'CUST-00852',
       'CUST-00402', 'CUST-00581', 'CUST-00670', 'CUST-00164',
       'CUST-00779', 'CUST-00038', 'CUST-00206', 'CUST-00353',
       'CUST-00747', 'CUST-00333', 'CUST-00665', 'CUST-00711',
       'CUST-00731', 'CUST-00743', 'CUST-00668', 'CUST-00463',
       'CUST-00194', 'CUST-00264', 'CUST-00627', 'CUST-00888',
       'CUST-00672', 'CUST-00548', 'CUST-00896', 'CUST-00298',
       'CUST-00515', 'CUST-00272', 'CUST-00025', 'CUST-00331',
       'CUST-00735', 'CUST-00335', 'CUST-00197', 'CUST-00827',
       'CUST-00167', 'CUST-00585', 'CUST-00126', 'CUST-00577',
       'CUST-00475', 'CUST-00884', 'CUST-00813', 'CUST-00893',
       'CUST-00068', 'CUST-00610', 'CUST-00001', 'CUST-00469',
       'CUST-00608', 'CUST-00601', 'CUST-00233', 'CUST-00468',
       'CUST-00728', 'CUST-00726', 'CUST-00143', 'CUST-00498',
       'CUST-00245', 'CUST-00162', 'CUST-00513', 'CUST-00833',
       'CUST-00108', 'CUST-00302', 'CUST-00721', 'CUST-00506',
       'CUST-00572', 'CUST-00351', 'CUST-00551', 'CUST-00441',
       'CUST-00199', 'CUST-00165', 'CUST-00574', 'CUST-00889',
       'CUST-00097', 'CUST-00832', 'CUST-00212', 'CUST-00324',
       'CUST-00385', 'CUST-00689', 'CUST-00086', 'CUST-00812',
       'CUST-00628', 'CUST-00890', 'CUST-00894', 'CUST-00227',
       'CUST-00074', 'CUST-00195', 'CUST-00344', 'CUST-00457',
       'CUST-00447', 'CUST-00481', 'CUST-00152', 'CUST-00238',
       'CUST-00570', 'CUST-00350', 'CUST-00059', 'CUST-00037',
       'CUST-00118', 'CUST-00246', 'CUST-00204', 'CUST-00729',
       'CUST-00446', 'CUST-00148', 'CUST-00820', 'CUST-00707',
       'CUST-00868', 'CUST-00757', 'CUST-00265', 'CUST-00857',
       'CUST-00737', 'CUST-00024', 'CUST-00100', 'CUST-00102',
       'CUST-00674', 'CUST-00398', 'CUST-00107', 'CUST-00638',
       'CUST-00762', 'CUST-00366', 'CUST-00456', 'CUST-00273',
       'CUST-00555', 'CUST-00738', 'CUST-00157', 'CUST-00010',
       'CUST-00540', 'CUST-00232', 'CUST-00609', 'CUST-00401',
       'CUST-00846', 'CUST-00696', 'CUST-00568', 'CUST-00339',
       'CUST-00494', 'CUST-00318', 'CUST-00002', 'CUST-00048',
       'CUST-00575', 'CUST-00190', 'CUST-00804', 'CUST-00355',
       'CUST-00473', 'CUST-00405', 'CUST-00052', 'CUST-00622',
       'CUST-00313', 'CUST-00399', 'CUST-00112', 'CUST-00346',
       'CUST-00295', 'CUST-00006', 'CUST-00070', 'CUST-00255',
       'CUST-00693', 'CUST-00061', 'CUST-00763', 'CUST-00129',
       'CUST-00782', 'CUST-00309', 'CUST-00811', 'CUST-00588',
       'CUST-00587', 'CUST-00802', 'CUST-00870', 'CUST-00876',
       'CUST-00383', 'CUST-00534', 'CUST-00454', 'CUST-00166',
       'CUST-00897', 'CUST-00044', 'CUST-00041', 'CUST-00177',
       'CUST-00437', 'CUST-00075', 'CUST-00504', 'CUST-00462',
       'CUST-00569', 'CUST-00092', 'CUST-00393', 'CUST-00604',
       'CUST-00710', 'CUST-00600', 'CUST-00087', 'CUST-00181',
       'CUST-00545', 'CUST-00560', 'CUST-00586', 'CUST-00644',
       'CUST-00349', 'CUST-00156', 'CUST-00022', 'CUST-00698',
       'CUST-00382', 'CUST-00853', 'CUST-00291', 'CUST-00360',
       'CUST-00874', 'CUST-00240', 'CUST-00357', 'CUST-00033',
       'CUST-00275', 'CUST-00843', 'CUST-00603', 'CUST-00387',
       'CUST-00076', 'CUST-00423', 'CUST-00375', 'CUST-00486',
       'CUST-00477', 'CUST-00453', 'CUST-00117', 'CUST-00364',
       'CUST-00856', 'CUST-00491', 'CUST-00563', 'CUST-00756',
       'CUST-00378', 'CUST-00248', 'CUST-00305', 'CUST-00769',
       'CUST-00263', 'CUST-00881', 'CUST-00278', 'CUST-00091',
       'CUST-00688', 'CUST-00090', 'CUST-00207', 'CUST-00770',
       'CUST-00796', 'CUST-00089', 'CUST-00400', 'CUST-00787',
       'CUST-00749', 'CUST-00686', 'CUST-00679', 'CUST-00878',
       'CUST-00701', 'CUST-00704', 'CUST-00179', 'CUST-00773',
       'CUST-00429', 'CUST-00834', 'CUST-00310', 'CUST-00789',
       'CUST-00845', 'CUST-00682', 'CUST-00819', 'CUST-00590',
       'CUST-00543', 'CUST-00395', 'CUST-00200', 'CUST-00365',
       'CUST-00858', 'CUST-00712', 'CUST-00559', 'CUST-00281',
       'CUST-00183', 'CUST-00825', 'CUST-00184', 'CUST-00640',
       'CUST-00541', 'CUST-00772', 'CUST-00633', 'CUST-00146',
       'CUST-00151', 'CUST-00485', 'CUST-00424', 'CUST-00629',
       'CUST-00690', 'CUST-00699', 'CUST-00345', 'CUST-00211',
       'CUST-00797', 'CUST-00733', 'CUST-00163', 'CUST-00505',
       'CUST-00565', 'CUST-00589', 'CUST-00426', 'CUST-00105',
       'CUST-00510', 'CUST-00500', 'CUST-00887', 'CUST-00599',
       'CUST-00226', 'CUST-00823', 'CUST-00407', 'CUST-00776',
       'CUST-00193', 'CUST-00871', 'CUST-00487', 'CUST-00187',
       'CUST-00363', 'CUST-00492', 'CUST-00470', 'CUST-00607',
       'CUST-00576', 'CUST-00436', 'CUST-00062', 'CUST-00306',
       'CUST-00775', 'CUST-00748', 'CUST-00137', 'CUST-00799',
       'CUST-00266', 'CUST-00809', 'CUST-00130', 'CUST-00495',
       'CUST-00381', 'CUST-00134', 'CUST-00546', 'CUST-00800',
       'CUST-00230', 'CUST-00214', 'CUST-00169', 'CUST-00821',
       'CUST-00077', 'CUST-00458', 'CUST-00855', 'CUST-00662',
       'CUST-00765', 'CUST-00860', 'CUST-00883', 'CUST-00718',
       'CUST-00271', 'CUST-00367', 'CUST-00391', 'CUST-00766',
       'CUST-00235', 'CUST-00452', 'CUST-00283', 'CUST-00031',
       'CUST-00170', 'CUST-00155', 'CUST-00496', 'CUST-00745',
       'CUST-00030'], dtype=object)

In [70]:
#5. How many unique cities, branches and employment categories are represented?
df["City"].nunique()
df["Branch_Name"].nunique()
df["Employment_Type"].nunique()

5

In [71]:
#6. How many loan records belong to each loan type?
df["Loan_Type"].value_counts()

Loan_Type
Personal Loan     356
Vehicle Loan      242
Home Loan         204
Business Loan     167
Education Loan    120
Gold Loan         111
Name: count, dtype: int64

In [22]:
#7. What percentage of the total loan records belongs to each loan type?

In [77]:
#8. Which loan type has the highest and lowest number of loan records?
df["Loan_Type"].value_counts().idxmax()
df["Loan_Type"].value_counts().idxmin()

'Gold Loan'

In [78]:
#9. How many loan accounts fall under each payment-status category?
df["Payment_Status"].value_counts()

Payment_Status
On Time    389
Closed     385
Late       229
Missed     197
Name: count, dtype: int64

In [21]:
#10. What percentage of accounts are on time, late, missed or closed?

In [80]:
#11. How many accounts fall under each risk category?
df["Risk_Category"].value_counts()

Risk_Category
Medium    504
Low       494
High      202
Name: count, dtype: int64

In [81]:
#12. What percentage of loan accounts are marked as defaulted?
df["Default_Flag"].value_counts(normalize=True) * 100

Default_Flag
No     82.25
Yes    17.75
Name: proportion, dtype: float64

In [82]:
#13. Which five cities have the highest number of loan accounts?
df["City"].value_counts().head(5)

City
Mumbai       248
Pune         166
Bengaluru     85
Delhi         81
Thane         74
Name: count, dtype: int64

In [83]:
#14. How many unique customers are present in each city?
df.groupby("City")["Customer_ID"].nunique()

City
Ahmedabad     46
Bengaluru     81
Chennai       57
Delhi         78
Hyderabad     69
Indore        45
Jaipur        48
Kolkata       47
Lucknow       47
Mumbai       212
Nagpur        60
Nashik        57
Pune         152
Surat         51
Thane         71
Name: Customer_ID, dtype: int64

In [84]:
#15. Which employment type has the highest number of borrowers?
df["Employment_Type"].value_counts()

Employment_Type
Salaried               563
Self-Employed          208
Business Owner         168
Freelancer             145
Government Employee    116
Name: count, dtype: int64

In [85]:
#16. Which payment mode is used most frequently?
df["Payment_Mode"].value_counts().idxmax()

'Auto-Debit'

In [86]:
#17. Which acquisition channel generates the highest number of loan records?
df["Acquisition_Channel"].value_counts().idxmax()

'Mobile App'

In [87]:
#18. Which five branches handle the highest number of loan accounts?
df["Branch_Name"].value_counts().head(5)

Branch_Name
Nagpur Civil Lines       134
Nashik Road              130
Pune Central             129
Bengaluru MG Road        122
Ahmedabad Navrangpura    120
Name: count, dtype: int64

In [88]:
#19. What is the total sanctioned loan amount for each loan type?
df.groupby("Loan_Type")["Loan_Amount_INR"].sum()

Loan_Type
Business Loan     338690000
Education Loan    169825000
Gold Loan          53425000
Home Loan         937635000
Personal Loan     187300000
Vehicle Loan      323160000
Name: Loan_Amount_INR, dtype: int64

In [89]:
#20. Which loan type has the highest total sanctioned loan amount?
df.groupby("Loan_Type")["Loan_Amount_INR"].sum().idxmax()

'Home Loan'

In [90]:
#21. What are the average and median loan amounts for each loan type?
df.groupby("Loan_Type")["Loan_Amount_INR"].agg(["mean", "median"])

                        mean     median
Loan_Type
Business Loan   2.028084e+06  1830000.0
Education Loan  1.415208e+06  1332500.0
Gold Loan       4.813063e+05   385000.0
Home Loan       4.596250e+06  4235000.0
Personal Loan   5.261236e+05   460000.0
Vehicle Loan    1.335372e+06  1210000.0

In [91]:
#22. What are the minimum and maximum loan amounts for each loan type?
df.groupby("Loan_Type")["Loan_Amount_INR"].agg(["min", "max"])

                   min       max
Loan_Type
Business Loan   250000   5400000
Education Loan  140000   3735000
Gold Loan        45000   1420000
Home Loan       920000  11270000
Personal Loan    65000   1430000
Vehicle Loan    185000   3120000

In [92]:
#23. What is the average interest rate for each loan type?
df.groupby("Loan_Type")["Interest_Rate_Pct"].mean()

Loan_Type
Business Loan     16.910487
Education Loan    11.779373
Gold Loan         13.607700
Home Loan          9.546699
Personal Loan     16.656390
Vehicle Loan      11.806721
Name: Interest_Rate_Pct, dtype: float64

In [93]:
#24. Which loan type has the highest average monthly EMI?
df.groupby("Loan_Type")["Monthly_EMI_INR"].mean()

Loan_Type
Business Loan     84940.635509
Education Loan    26300.832083
Gold Loan         36128.699459
Home Loan         58016.474657
Personal Loan     23593.630899
Vehicle Loan      34687.824545
Name: Monthly_EMI_INR, dtype: float64

In [94]:
#25. What is the total outstanding balance for each loan type?
df.groupby("Loan_Type")["Outstanding_Balance_INR"].sum()

Loan_Type
Business Loan     1.273775e+08
Education Loan    1.101274e+08
Gold Loan         1.101567e+07
Home Loan         7.706345e+08
Personal Loan     7.278132e+07
Vehicle Loan      1.500851e+08
Name: Outstanding_Balance_INR, dtype: float64

In [95]:
#26. Which payment-status category has the highest total outstanding balance?
df.groupby("Payment_Status")["Outstanding_Balance_INR"].sum()

Payment_Status
Closed     5.172970e+06
Late       4.060937e+08
Missed     4.395105e+08
On Time    3.912443e+08
Name: Outstanding_Balance_INR, dtype: float64

In [96]:
#27. What is the average outstanding balance for on-time, late, missed and closed accounts?
df.groupby("Payment_Status")["Outstanding_Balance_INR"].mean()

Payment_Status
Closed     1.343629e+04
Late       1.773335e+06
Missed     2.231018e+06
On Time    1.005769e+06
Name: Outstanding_Balance_INR, dtype: float64

In [97]:
#28. What is the average credit score for each loan type?
df.groupby("Loan_Type")["Credit_Score"].mean()

Loan_Type
Business Loan     681.172806
Education Loan    680.746212
Gold Loan         674.426517
Home Loan         682.446227
Personal Loan     684.050732
Vehicle Loan      692.338968
Name: Credit_Score, dtype: float64

In [98]:
#29. What is the average credit score for each employment category?
df.groupby("Employment_Type")["Credit_Score"].mean()

Employment_Type
Business Owner         691.160895
Freelancer             662.269175
Government Employee    700.791884
Salaried               687.968190
Self-Employed          672.268551
Name: Credit_Score, dtype: float64

In [99]:
#30. What are the average and median annual incomes for each employment category?
df.groupby("Employment_Type")["Annual_Income_INR"].agg(["mean", "median"])

                             mean        median
Employment_Type
Business Owner       2.984251e+06  2.640500e+06
Freelancer           9.110445e+05  8.820000e+05
Government Employee  1.039967e+06  1.000000e+06
Salaried             1.093905e+06  1.020000e+06
Self-Employed        1.443450e+06  1.386089e+06

In [100]:
#31. What is the average debt-to-income ratio for each risk category?
df.groupby("Risk_Category")["Debt_to_Income_Ratio"].mean()

Risk_Category
High      0.762786
Low       0.331235
Medium    0.627882
Name: Debt_to_Income_Ratio, dtype: float64

In [101]:
#32. How do average credit score, annual income and loan amount vary across risk categories?
df.groupby("Risk_Category")[["Credit_Score",
                                   "Annual_Income_INR",
                                   "Loan_Amount_INR"]].mean()

               Credit_Score  Annual_Income_INR  Loan_Amount_INR
Risk_Category
High             637.274127       9.624176e+05     3.113069e+06
Low              718.371958       1.698481e+06     9.259717e+05
Medium           668.628467       1.263373e+06     1.832867e+06

In [102]:
#33. How many high-risk loan accounts are present in each city?
df[df["Risk_Category"]=="High"].groupby("City").size()

City
Ahmedabad     7
Bengaluru    15
Chennai      12
Delhi        14
Hyderabad     4
Indore        9
Jaipur        6
Kolkata       7
Lucknow      11
Mumbai       35
Nagpur       13
Nashik       14
Pune         38
Surat         7
Thane        10
dtype: int64

In [103]:
#34. Which loan type has the highest number of defaulted accounts?
df.groupby("Loan_Type")["Default_Flag"].sum()

Loan_Type
Business Loan     NoNoNoNoNoYesNoNoNoNoYesNoNoYesNoNoNoYesNoNoNo...
Education Loan    YesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNo...
Gold Loan         NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNo...
Home Loan         YesNoNoNoNoNoYesNoNoYesYesYesNoNoNoNoNoNoYesYe...
Personal Loan     NoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoYesYesNoYes...
Vehicle Loan      NoNoYesNoNoNoYesNoNoYesNoYesNoNoNoNoNoYesNoYes...
Name: Default_Flag, dtype: object

In [18]:
#35. What is the default percentage for each loan type?

In [20]:
#36. Which employment category has the highest default percentage?

In [17]:
#37. Which loan type has the highest number of late or missed-payment accounts?

In [106]:
#38. What are the top ten customers by total sanctioned loan amount?
df.groupby("Customer_ID")["Loan_Amount_INR"].sum().nlargest(10)

Customer_ID
CUST-00049    16020000
CUST-00539    14405000
CUST-00873    13645000
CUST-00174    13095000
CUST-00223    12930000
CUST-00318    12785000
CUST-00528    12565000
CUST-00217    12445000
CUST-00267    12155000
CUST-00867    12080000
Name: Loan_Amount_INR, dtype: int64

In [16]:
#39. What are the top ten loan accounts by outstanding balance?

In [14]:
#40. How do the number and total value of loan disbursements vary by year and loan type?