In [2]:
# Importing the required libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Loading the training dataset
df = pd.read_csv("/Users/keva/Downloads/warehouse_inventory_clustering_dataset.csv")

In [3]:
# Displaying the first 5 rows of the dataset

df.head()

,item_id,category,subcategory,supplier_id,warehouse_zone,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,...,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
0,ITM00001,Grocery,Snacks,S1036,B2,310,0.26,7.8,0.05,8,...,0.012,10.83,132.98,1,2,249,75,46,33112.02,161.12
1,ITM00002,Industrial,Electrical Parts,S1036,B1,455,0.16,4.8,0.08,8,...,0.007,45.57,1525.56,0,0,362,94,34,552252.72,141.27
2,ITM00003,Apparel,Jackets,S1011,B2,350,0.43,20.9,0.57,6,...,0.010,18.47,457.56,3,9,317,105,146,145046.52,238.29
3,ITM00004,Automotive,Lubricants,S1030,A1,121,0.33,4.6,0.12,1,...,0.017,168.71,1779.38,0,1,183,32,84,325626.54,87.90
4,ITM00005,Pharmaceutical,Medical Devices,S1064,A2,85,0.14,7.3,0.15,1,...,0.016,33.33,731.83,2,4,209,17,180,152952.47,86.85

In [4]:
# Displaying the last 5 rows of the dataset

df.tail()

,item_id,category,subcategory,supplier_id,warehouse_zone,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,...,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
3995,ITM03996,Pharmaceutical,OTC Medicine,S1003,C2,61,0.33,7.3,0.35,3,...,0.019,12.12,404.91,0,0,274,16,248,110945.34,28.77
3996,ITM03997,Automotive,Batteries,S1007,C1,487,0.40,13.8,0.50,6,...,0.026,45.95,844.98,10,5,371,141,18,313487.58,245.03
3997,ITM03998,Industrial,Fasteners,S1064,D2,32,0.61,10.9,0.36,2,...,0.020,60.67,1743.43,2,2,200,12,174,348686.00,56.08
3998,ITM03999,Stationery,Writing Tools,S1056,D1,571,0.42,11.8,0.41,11,...,0.015,4.62,132.21,5,12,511,170,52,67559.31,200.31
3999,ITM04000,Pharmaceutical,OTC Medicine,S1022,A1,540,0.13,6.4,0.08,7,...,0.018,11.49,218.83,2,1,453,106,8,99129.99,130.47

In [5]:
# Checking the data types of all columns

df.dtypes

item_id                             object
category                            object
subcategory                         object
supplier_id                         object
warehouse_zone                      object
avg_monthly_demand                   int64
demand_variability                 float64
avg_lead_time_days                 float64
lead_time_variability              float64
monthly_reorder_count                int64
stock_turnover_ratio               float64
days_in_inventory                    int64
stockout_frequency                   int64
backorder_frequency                  int64
return_rate                        float64
damage_rate                        float64
holding_cost_per_unit              float64
unit_cost                          float64
reorder_point_breaches               int64
supplier_delay_incidents             int64
current_stock                        int64
safety_stock                         int64
excess_stock_level                   int64
inventory_value                    float64
warehouse_demand_pressure_index    float64
dtype: object

In [6]:
# Getting basic information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   item_id                          4000 non-null   object
 1   category                         4000 non-null   object
 2   subcategory                      4000 non-null   object
 3   supplier_id                      4000 non-null   object
 4   warehouse_zone                   4000 non-null   object
 5   avg_monthly_demand               4000 non-null   int64
 6   demand_variability               4000 non-null   float64
 7   avg_lead_time_days               4000 non-null   float64
 8   lead_time_variability            4000 non-null   float64
 9   monthly_reorder_count            4000 non-null   int64
 10  stock_turnover_ratio             4000 non-null   float64
 11  days_in_inventory                4000 non-null   int64
 12  stockout_frequency               4000 non-null   int64
 13  backorder_frequency              4000 non-null   int64
 14  return_rate                      4000 non-null   float64
 15  damage_rate                      4000 non-null   float64
 16  holding_cost_per_unit            4000 non-null   float64
 17  unit_cost                        4000 non-null   float64
 18  reorder_point_breaches           4000 non-null   int64
 19  supplier_delay_incidents         4000 non-null   int64
 20  current_stock                    4000 non-null   int64
 21  safety_stock                     4000 non-null   int64
 22  excess_stock_level               4000 non-null   int64
 23  inventory_value                  4000 non-null   float64
 24  warehouse_demand_pressure_index  4000 non-null   float64
dtypes: float64(10), int64(10), object(5)
memory usage: 781.4+ KB

In [7]:
# Checking for missing values in each column

df.isnull().sum()

item_id                            0
category                           0
subcategory                        0
supplier_id                        0
warehouse_zone                     0
avg_monthly_demand                 0
demand_variability                 0
avg_lead_time_days                 0
lead_time_variability              0
monthly_reorder_count              0
stock_turnover_ratio               0
days_in_inventory                  0
stockout_frequency                 0
backorder_frequency                0
return_rate                        0
damage_rate                        0
holding_cost_per_unit              0
unit_cost                          0
reorder_point_breaches             0
supplier_delay_incidents           0
current_stock                      0
safety_stock                       0
excess_stock_level                 0
inventory_value                    0
warehouse_demand_pressure_index    0
dtype: int64

In [8]:
# Removing duplicate rows if any duplicates are present

df = df.drop_duplicates()

In [9]:
# Checking the dataset size after removing duplicates

df.shape

(4000, 25)

In [10]:
# Getting statistical summary of numerical columns

df.describe()

,avg_monthly_demand,demand_variability,avg_lead_time_days,lead_time_variability,monthly_reorder_count,stock_turnover_ratio,days_in_inventory,stockout_frequency,backorder_frequency,return_rate,damage_rate,holding_cost_per_unit,unit_cost,reorder_point_breaches,supplier_delay_incidents,current_stock,safety_stock,excess_stock_level,inventory_value,warehouse_demand_pressure_index
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4.000000e+03,4000.00000
mean,331.809250,0.285640,10.301275,0.258738,4.707250,5.944282,65.489750,2.491250,1.938000,0.028485,0.015713,47.709973,804.380267,2.657250,3.239750,317.102000,80.002750,104.915750,2.491254e+05,159.10009
std,228.438284,0.128173,5.592473,0.165963,2.991118,3.804082,56.855528,3.192487,2.503642,0.015560,0.008412,50.174326,741.472968,3.498976,3.615873,136.958627,55.192937,106.302228,2.508303e+05,88.27321
min,1.000000,0.080000,1.000000,0.050000,0.000000,0.200000,4.000000,0.000000,0.000000,0.005000,0.002000,0.520000,20.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000e+00,5.00000
25%,103.000000,0.190000,6.200000,0.130000,2.000000,2.140000,22.000000,0.000000,0.000000,0.017000,0.009000,12.565000,220.160000,0.000000,0.000000,219.000000,27.000000,32.000000,6.278350e+04,82.77000
50%,333.000000,0.260000,9.000000,0.200000,5.000000,6.150000,34.000000,1.000000,1.000000,0.026000,0.015000,33.710000,652.130000,1.000000,2.000000,304.000000,80.000000,60.000000,1.759532e+05,151.79500
75%,523.250000,0.370000,13.400000,0.360000,7.000000,9.140000,106.000000,4.000000,3.000000,0.037000,0.020000,64.495000,1108.817500,4.000000,5.000000,403.000000,122.000000,150.000000,3.498038e+05,228.21000
max,983.000000,0.620000,35.000000,0.720000,14.000000,15.890000,273.000000,15.000000,14.000000,0.080000,0.040000,502.570000,6085.330000,17.000000,18.000000,908.000000,306.000000,622.000000,2.093354e+06,300.00000

# ASSESSMENT QUESTIONS:

In [4]:
# Q1: How does average monthly demand vary across different product categories?

df.groupby('category')['avg_monthly_demand'].mean().sort_values(ascending=False)

category
Pharmaceutical    354.012024
Industrial        342.108108
Home & Kitchen    335.700405
Automotive        333.521822
Apparel           331.339216
Stationery        327.657895
Grocery           317.458696
Electronics       311.032129
Name: avg_monthly_demand, dtype: float64

In [11]:
# Q2: Which product categories show the highest demand variability?

df.groupby('category')['demand_variability'].mean().sort_values(ascending=False)

category
Electronics       0.295663
Grocery           0.291500
Home & Kitchen    0.287652
Automotive        0.287173
Stationery        0.287045
Industrial        0.280637
Pharmaceutical    0.278337
Apparel           0.277902
Name: demand_variability, dtype: float64

In [12]:
# Q3: Which warehouse zones handle products with the highest average demand?

df.groupby('warehouse_zone')['avg_monthly_demand'].mean().sort_values(ascending=False)

warehouse_zone
D1    344.346939
C2    340.298805
B2    338.925847
C1    330.073260
B1    328.317719
A1    325.836327
D2    324.181633
A2    323.202756
Name: avg_monthly_demand, dtype: float64

In [5]:
# Q4: Which products have the longest average supplier lead times?

df[['item_id', 'avg_lead_time_days']].sort_values('avg_lead_time_days', ascending=False).head(10)

       item_id  avg_lead_time_days
1916  ITM01917                35.0
1308  ITM01309                35.0
39    ITM00040                35.0
379   ITM00380                33.9
925   ITM00926                33.6
2558  ITM02559                32.0
3566  ITM03567                31.9
1664  ITM01665                30.8
1788  ITM01789                30.6
331   ITM00332                30.6

In [20]:
# Q5: Is high lead-time variability associated with more supplier delay incidents?

print("Correlation:", round(df['lead_time_variability'].corr(df['supplier_delay_incidents']), 2))

Correlation: 0.72

In [7]:
# Q6: Which products have the highest stock turnover ratios?

df[['item_id', 'stock_turnover_ratio']].sort_values('stock_turnover_ratio', ascending=False).head(10)

       item_id  stock_turnover_ratio
426   ITM00427                 15.89
2464  ITM02465                 15.69
2779  ITM02780                 15.34
1418  ITM01419                 15.18
2842  ITM02843                 15.01
1128  ITM01129                 15.00
3702  ITM03703                 15.00
3621  ITM03622                 15.00
3404  ITM03405                 15.00
1765  ITM01766                 14.94

In [8]:
# Q7: Which products remain in inventory for the longest number of days?

df[['item_id', 'days_in_inventory']].sort_values('days_in_inventory', ascending=False).head(10)

       item_id  days_in_inventory
643   ITM00644                273
2772  ITM02773                272
3078  ITM03079                268
680   ITM00681                261
3722  ITM03723                258
1179  ITM01180                252
2295  ITM02296                249
547   ITM00548                247
1373  ITM01374                246
2693  ITM02694                246

In [21]:
# Q8: Is there a relationship between stock turnover ratio and days in inventory?

print("Correlation:", round(df['stock_turnover_ratio'].corr(df['days_in_inventory']), 2))

Correlation: -0.76

In [10]:
# Q9: Which products experience the highest stockout frequency?

df[['item_id', 'stockout_frequency']].sort_values('stockout_frequency', ascending=False).head(10)

       item_id  stockout_frequency
2971  ITM02972                  15
3757  ITM03758                  15
3422  ITM03423                  15
3624  ITM03625                  15
2849  ITM02850                  15
1626  ITM01627                  15
2284  ITM02285                  15
2255  ITM02256                  15
2536  ITM02537                  15
1901  ITM01902                  15

In [22]:
# Q10: Are products with high demand variability more likely to experience stockouts?

print("Correlation:", round(df['demand_variability'].corr(df['stockout_frequency']), 2))

Correlation: 0.37

In [12]:
# Q11: Which products experience frequent backorders?

df[['item_id', 'backorder_frequency']].sort_values('backorder_frequency', ascending=False).head(10)

       item_id  backorder_frequency
1458  ITM01459                   14
1871  ITM01872                   13
3741  ITM03742                   13
3981  ITM03982                   13
2143  ITM02144                   13
3812  ITM03813                   13
2374  ITM02375                   13
1993  ITM01994                   12
3097  ITM03098                   12
3092  ITM03093                   12

In [23]:
# Q12: Is backorder frequency associated with stockout frequency?

print("Correlation:", round(df['backorder_frequency'].corr(df['stockout_frequency']), 2))

Correlation: 0.66

In [14]:
# Q13: Which products have the highest reorder-point breaches?

df[['item_id', 'reorder_point_breaches']].sort_values('reorder_point_breaches', ascending=False).head(10)

       item_id  reorder_point_breaches
241   ITM00242                      17
648   ITM00649                      17
2341  ITM02342                      16
1547  ITM01548                      16
3236  ITM03237                      16
3246  ITM03247                      15
1143  ITM01144                      15
2824  ITM02825                      15
2269  ITM02270                      15
2157  ITM02158                      15

In [24]:
# Q14: Do products with frequent reorder-point breaches also have high monthly reorder counts?

print("Correlation:", round(df['reorder_point_breaches'].corr(df['monthly_reorder_count']), 2))

Correlation: 0.34

In [16]:
# Q15: Which products have the highest supplier delay incidents?

df[['item_id', 'supplier_delay_incidents']].sort_values('supplier_delay_incidents', ascending=False).head(10)

       item_id  supplier_delay_incidents
1305  ITM01306                        18
1805  ITM01806                        18
2229  ITM02230                        17
191   ITM00192                        17
2515  ITM02516                        16
365   ITM00366                        16
2622  ITM02623                        16
1127  ITM01128                        16
1475  ITM01476                        16
3161  ITM03162                        15

In [17]:
# Q16: Is supplier delay associated with increased stockouts or backorders?

print("Supplier delay vs stockouts:",
      round(df['supplier_delay_incidents'].corr(df['stockout_frequency']), 2))

print("Supplier delay vs backorders:",
      round(df['supplier_delay_incidents'].corr(df['backorder_frequency']), 2))

Supplier delay vs stockouts: 0.61
Supplier delay vs backorders: 0.57

In [18]:
# Q17: Which products maintain significantly higher safety stock relative to their current stock?

df['safety_stock_ratio'] = df['safety_stock'] / df['current_stock']
df[['item_id', 'safety_stock_ratio']].sort_values( 'safety_stock_ratio', ascending=False).head(10)

       item_id  safety_stock_ratio
1475  ITM01476                 inf
2472  ITM02473                 inf
1625  ITM01626                 inf
1176  ITM01177                 inf
3981  ITM03982                 inf
3007  ITM03008           18.000000
493   ITM00494            9.666667
2617  ITM02618            7.050000
1539  ITM01540            3.750000
1986  ITM01987            2.815789

In [19]:
# Q18: Which products have high excess-stock levels?

df[['item_id', 'excess_stock_level']].sort_values('excess_stock_level', ascending=False).head(10)

       item_id  excess_stock_level
1018  ITM01019                 622
2017  ITM02018                 591
1375  ITM01376                 568
2014  ITM02015                 542
2509  ITM02510                 539
3529  ITM03530                 536
2314  ITM02315                 503
3405  ITM03406                 495
1171  ITM01172                 487
3061  ITM03062                 484

In [25]:
# Q19: Is excess stock associated with high days in inventory?

print("Correlation:", round(df['excess_stock_level'].corr(df['days_in_inventory']), 2))

Correlation: 0.73

In [26]:
# Q20: Which products have the highest inventory value?

df[['item_id', 'inventory_value']].sort_values('inventory_value', ascending=False).head(10)

       item_id  inventory_value
1253  ITM01254       2093353.52
155   ITM00156       1993974.96
706   ITM00707       1905333.80
3469  ITM03470       1902986.23
3718  ITM03719       1775518.85
1077  ITM01078       1699984.38
3085  ITM03086       1687486.24
1182  ITM01183       1632093.78
1598  ITM01599       1590946.24
3735  ITM03736       1563724.36

In [30]:
# Q21: Which products have the highest holding cost per unit?

df[['item_id', 'holding_cost_per_unit']].sort_values('holding_cost_per_unit', ascending=False).head(10)

       item_id  holding_cost_per_unit
1253  ITM01254                 502.57
2257  ITM02258                 477.00
3547  ITM03548                 470.56
3735  ITM03736                 468.89
1977  ITM01978                 427.05
706   ITM00707                 391.89
3590  ITM03591                 390.88
2765  ITM02766                 380.79
2709  ITM02710                 377.69
3663  ITM03664                 353.22

In [27]:
# Q22: Do expensive products tend to have lower or higher stock turnover?

print("Correlation:", round(df['unit_cost'].corr(df['stock_turnover_ratio']), 2))

Correlation: -0.15

In [32]:
# Q23: Which products have the highest return rates?

df[['item_id', 'return_rate']].sort_values('return_rate', ascending=False).head(10)

       item_id  return_rate
2359  ITM02360        0.080
2961  ITM02962        0.080
2623  ITM02624        0.080
2584  ITM02585        0.080
3520  ITM03521        0.079
823   ITM00824        0.079
2123  ITM02124        0.079
371   ITM00372        0.079
889   ITM00890        0.079
462   ITM00463        0.079

In [33]:
# Q24: Which products have the highest damage rates?

df[['item_id', 'damage_rate']].sort_values('damage_rate', ascending=False).head(10)

       item_id  damage_rate
1405  ITM01406         0.04
702   ITM00703         0.04
2627  ITM02628         0.04
1589  ITM01590         0.04
1160  ITM01161         0.04
2277  ITM02278         0.04
2813  ITM02814         0.04
1471  ITM01472         0.04
2055  ITM02056         0.04
3288  ITM03289         0.04

In [34]:
# Q25: Are high return and damage rates concentrated in particular categories or warehouse zones?

print("Return and damage rates by category:")
print(df.groupby('category')[['return_rate', 'damage_rate']].mean())

print("\nReturn and damage rates by warehouse zone:")
print(df.groupby('warehouse_zone')[['return_rate', 'damage_rate']].mean())

Return and damage rates by category:
                return_rate  damage_rate
category
Apparel            0.027494     0.015663
Automotive         0.028767     0.015972
Electronics        0.029620     0.015857
Grocery            0.028346     0.015689
Home & Kitchen     0.029095     0.015636
Industrial         0.028432     0.015564
Pharmaceutical     0.028216     0.014996
Stationery         0.027907     0.016324

Return and damage rates by warehouse zone:
                return_rate  damage_rate
warehouse_zone
A1                 0.028317     0.016032
A2                 0.028528     0.016478
B1                 0.029092     0.015939
B2                 0.028460     0.015769
C1                 0.027777     0.014905
C2                 0.028894     0.015542
D1                 0.027563     0.015376
D2                 0.029318     0.015727

In [35]:
# Q26: Which products have the highest warehouse demand pressure index?

df[['item_id', 'warehouse_demand_pressure_index']].sort_values('warehouse_demand_pressure_index', ascending=False).head(10)

       item_id  warehouse_demand_pressure_index
2152  ITM02153                            300.0
3377  ITM03378                            300.0
3317  ITM03318                            300.0
3313  ITM03314                            300.0
3306  ITM03307                            300.0
3304  ITM03305                            300.0
3298  ITM03299                            300.0
3294  ITM03295                            300.0
824   ITM00825                            300.0
2002  ITM02003                            300.0